services:

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  servicea:
    build: ./servicea
    container_name: servicea
    depends_on:
      - rabbitmq
    entrypoint: ["./wait-for-it.sh", "rabbitmq:5672", "--timeout=30", "--", "java", "-jar", "app.jar"]
    ports:
      - "8081:8081"

  serviceb:
    build: ./serviceb
    container_name: serviceb
    depends_on:
      - rabbitmq
    entrypoint: ["./wait-for-it.sh", "rabbitmq:5672", "--timeout=30", "--", "java", "-jar", "app.jar"]
    ports:
      - "8082:8082"

  clientejava:
    build: ./clientejava
    container_name: clientejava
    depends_on:
      - rabbitmq
    entrypoint: ["./wait-for-it.sh", "rabbitmq:5672", "--timeout=30", "--", "java", "-jar", "app.jar"]
